/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.telalogin.Views;

import DAO.LoginDAO;
import DTO.UsuarioDTO;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
/**
 *
 * @author rafael
 */
public class LoginView extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public LoginView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        emailUsuarioLogin = new javax.swing.JLabel();
        senhaUsuarioLogin = new javax.swing.JLabel();
        resultado = new javax.swing.JLabel();
        txtEmailFieldLogin = new javax.swing.JTextField();
        txtSenhaFieldLogin = new javax.swing.JPasswordField();
        btnNovocadastrar = new javax.swing.JButton();
        btnEntrar = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        emailUsuarioLogin.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        emailUsuarioLogin.setForeground(new java.awt.Color(0, 0, 0));
        emailUsuarioLogin.setText("Email");

        senhaUsuarioLogin.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        senhaUsuarioLogin.setForeground(new java.awt.Color(0, 0, 0));
        senhaUsuarioLogin.setText("Password");

        resultado.setBackground(new java.awt.Color(0, 0, 0));
        resultado.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        resultado.setForeground(new java.awt.Color(0, 0, 0));
        resultado.setText("login");

        txtSenhaFieldLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaFieldLoginActionPerformed(evt);
            }
        });

        btnNovocadastrar.setBackground(new java.awt.Color(153, 153, 255));
        btnNovocadastrar.setText("Cadastrar");
        btnNovocadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovocadastrarActionPerformed(evt);
            }
        });

        btnEntrar.setBackground(new java.awt.Color(153, 153, 255));
        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailUsuarioLogin)
                            .addComponent(senhaUsuarioLogin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmailFieldLogin)
                            .addComponent(txtSenhaFieldLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(201, 201, 201)
                                .addComponent(resultado))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(btnNovocadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(137, 137, 137))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(resultado)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEmailFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailUsuarioLogin))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhaUsuarioLogin)
                    .addComponent(txtSenhaFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovocadastrar)
                    .addComponent(btnEntrar))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSenhaFieldLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaFieldLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaFieldLoginActionPerformed

    private void btnNovocadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovocadastrarActionPerformed
       CadastroView telaCadastro = new CadastroView();
       telaCadastro.setVisible(true);
       dispose();
    }//GEN-LAST:event_btnNovocadastrarActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
          logar();
    }//GEN-LAST:event_btnEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnNovocadastrar;
    private javax.swing.JLabel emailUsuarioLogin;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel resultado;
    private javax.swing.JLabel senhaUsuarioLogin;
    private javax.swing.JTextField txtEmailFieldLogin;
    private javax.swing.JPasswordField txtSenhaFieldLogin;
    // End of variables declaration//GEN-END:variables
private void logar(){
    try{ 
         String email,senha;
       
       email = txtEmailFieldLogin.getText();
       senha = txtSenhaFieldLogin.getText();
       
        UsuarioDTO usuarioLogado = new UsuarioDTO();
         usuarioLogado.setEmail(email);
         usuarioLogado.setSenha(senha);
         
        LoginDAO usuarioDAO = new LoginDAO();
         ResultSet resUsuariDao = usuarioDAO.autenticacao(usuarioLogado);
                 
                 if (resUsuariDao.next()) {
                   PerfilView telaPerfil = new PerfilView();
                   EditarView telaEditar = new EditarView();
                   UsuarioDTO DadosDosUsuarios = CapturarDados(resUsuariDao);
                   telaPerfil.capturarDados(DadosDosUsuarios);
                   telaEditar.PreencherCamposEditar(DadosDosUsuarios);
                   telaPerfil.setVisible(true);
                    dispose();
                  
                 }else{
                    
                    JOptionPane.showMessageDialog(null, "usuario ou senha inválidos");
                 }
    
     }catch (SQLException erro){
         JOptionPane.showMessageDialog(null, "FRMLOgin" + erro);
     }
            
}

private UsuarioDTO CapturarDados(ResultSet dadosDoUsuario ){
    UsuarioDTO usuarioAtual = new UsuarioDTO();
    try{
    usuarioAtual.setEmail(dadosDoUsuario.getString("email"));
    usuarioAtual.setNome(dadosDoUsuario.getString("nome"));
    usuarioAtual.setTelefone(dadosDoUsuario.getString("telefone"));
    usuarioAtual.setcPF(dadosDoUsuario.getString("cpf"));
    usuarioAtual.setSenha(dadosDoUsuario.getString("senha"));
    usuarioAtual.setIdUsuario(Integer.parseInt(dadosDoUsuario.getString("id_usuario")));
    }catch(SQLException erro){
        JOptionPane.showMessageDialog(null, "erro na busca de dados" + erro);
    }
    return usuarioAtual;
}
}
